In [1]:
!pip install pandas scikit-learn transformers torch

Requirement already satisfied: pandas in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (2.0.3)
Requirement already satisfied: scikit-learn in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (1.3.2)
Requirement already satisfied: transformers in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (5.0.0)
Requirement already satisfied: torch in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (2.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: numpy>=1.21.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from pandas) (1.24.3)
Requirement already satisfied: scipy>=1.5.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.1.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: filelock in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (3.20.3)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (1.3.5)
Requirement already satisfied: packaging>=20.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (2025.10.23)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.10.0)
Requirement already satisfied: certifi in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.10)
Requirement already satisfied: h11>=0.16 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from torch) (3.1.2)
Requirement already satisfied: six>=1.5 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: click>=8.0.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from typer-slim->transformers) (8.1.7)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from transformers import pipeline

In [6]:
import pandas as pd

software_df = pd.read_json("dataset.json")
nonsoftware_df = pd.read_json("non_related.json")

software_df.head()

   id                           prompt            skill difficulty
0   1  design chat application backend    file_handling     medium
1   2      implement kruskal algorithm           devops     medium
2   3       design notification system  data_structures     medium
3   4     implement jwt authentication           devops       hard
4   5      implement kruskal algorithm           devops     medium

In [7]:
software_df["text"] = software_df["prompt"]
software_df["label"] = "software"

software_df = software_df[["text","label"]]

In [8]:
nonsoftware_df["text"] = nonsoftware_df["prompt"]
nonsoftware_df["label"] = "not_scope"

nonsoftware_df = nonsoftware_df[["text","label"]]

In [9]:
dataset = pd.concat([software_df, nonsoftware_df], ignore_index=True)

dataset.head()

                              text     label
0  design chat application backend  software
1      implement kruskal algorithm  software
2       design notification system  software
3     implement jwt authentication  software
4      implement kruskal algorithm  software

In [10]:
dataset["label"].value_counts()

label
software     2000
not_scope     500
Name: count, dtype: int64

In [12]:
nonsoftware_df = nonsoftware_df.sample(2000, replace=True)
dataset = pd.concat([software_df, nonsoftware_df], ignore_index=True)

In [13]:
dataset = dataset.drop_duplicates(subset="text")

In [14]:
dataset = dataset.sample(frac=1).reset_index(drop=True)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    dataset["text"],
    dataset["label"],
    test_size=0.2,
    random_state=42
)

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [17]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_vec, y_train)

LogisticRegression(max_iter=1000)

In [18]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.9

In [19]:
import pickle

pickle.dump(model, open("scope_model.pkl","wb"))
pickle.dump(vectorizer, open("vectorizer.pkl","wb"))

In [20]:
def test_query(q):
    vec = vectorizer.transform([q])
    print("Prediction:", model.predict(vec)[0])

In [22]:
test_query("implement binary search in python")

Prediction: software

In [23]:
test_query("best pizza recipe")

Prediction: not_scope

In [24]:
pip install accelerate

Collecting accelerate
  Downloading accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.17 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from accelerate) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from accelerate) (7.0.0)
Requirement already satisfied: pyyaml in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from accelerate) (2.10.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from accelerate) (1.3.5)
Requirement already satisfied: safetensors>=0.4.3 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface_hub>=0.21.0->accelerate) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface_hub>=0.21.0->accelerate) (2026.1.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: shellingham in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.5.4)
Requirement already satisfied: tqdm>=4.42.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typer-slim in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface_hub>=0.21.0->accelerate) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: anyio in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.10.0)
Requirement already satisfied: certifi in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: h11>=0.16 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from torch>=2.0.0->accelerate) (3.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from anyio->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.3)
Requirement already satisfied: click>=8.0.0 in /Users/agnikdutta/.pyenv/versions/3.10.7/lib/python3.10/site-packages (from typer-slim->huggingface_hub>=0.21.0->accelerate) (8.1.7)
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.13.0

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.